version: '3.8'

services:

  # MySQL service
  mysql_next:
    image: mysql:8.0
    container_name: mysql_next
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3300:3306"
    networks:
      - laravel_network

  # Redis service
  redis_next:
    image: redis:latest
    container_name: redis_next
    ports:
      - "6370:6379"
    networks:
      - laravel_network

  # RabbitMQ service
  rabbitmq_next:
    image: "rabbitmq:management"
    container_name: rabbitmq_next
    ports:
      - "15670:15672"  # RabbitMQ management UI
      - "5670:5672"    # RabbitMQ default port
    networks:
      - laravel_network
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_password

  # Laravel App 1
  notification_app:
    build:
      context: ./
      dockerfile: ./docker/apache/NotificationService/Dockerfile
    container_name: notification_app
    depends_on:
      - mysql_next
      - redis_next
      - rabbitmq_next
    ports:
      - "8002:80"
    networks:
      - laravel_network
    volumes:
      - ./NotificationService:/var/www/html/NotificationService
      - ./docker/apache/NotificationService/000-default.conf:/etc/apache2/sites-available/000-default.conf

  # Laravel App 2
  user_app:
    build:
      context: ./
      dockerfile: ./docker/apache/UserService/Dockerfile
    container_name: user_app
    depends_on:
      - mysql_next
      - redis_next
      - rabbitmq_next
    ports:
      - "8001:80"
    networks:
      - laravel_network
    volumes:
      - ./UserService:/var/www/html/UserService
      - ./docker/apache/UserService/000-default.conf:/etc/apache2/sites-available/000-default.conf

  # Other services...

networks:
  laravel_network:
    driver: bridge